import React, { useState } from 'react';
import {
  FileText,
  Upload,
  Sparkles,
  ChevronDown,
  ChevronUp,
  CheckCircle2,
  XCircle,
  AlertOctagon,
  RefreshCw,
  BookOpen,
  Award,
  Send,
  HelpCircle,
} from 'lucide-react';

function createSamplePdfBlob() {
  const samplePdfContent = `%PDF-1.4
1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj
2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj
3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >> endobj
4 0 obj << /Length 600 >> stream
BT
/F1 12 Tf
72 700 Td
(MINISTRY OF STATISTICS AND PROGRAMME IMPLEMENTATION MoSPI) Tj
0 -20 Td
(TECHNICAL COMPENDIUM ON STATISTICAL CONCEPTS AND STANDARDS) Tj
0 -20 Td
(1. Gross Value Added GVA at basic prices is defined under SNA 2008 as output less intermediate consumption.) Tj
0 -20 Td
(GDP at market prices equals GVA at basic prices plus net product taxes product taxes minus product subsidies.) Tj
0 -20 Td
(2. Consumer Price Index CPI is compiled monthly with Base Year 2012 equals 100 using Laspeyres formulation.) Tj
0 -20 Td
(3. Producer Price Index PPI measures average changes over time in selling prices received by domestic producers.) Tj
0 -20 Td
(PPI sub-indices are used in national accounts deflation to convert current prices into constant volume estimates.) Tj
ET
endstream
endobj
5 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj
xref
0 6
0000000000 65535 f 
0000000009 00000 n 
0000000058 00000 n 
0000000115 00000 n 
0000000244 00000 n 
0000000896 00000 n 
trailer << /Size 6 /Root 1 0 R >>
startxref
968
%%EOF`;
  return new Blob([samplePdfContent], { type: 'application/pdf' });
}

export default function StatutoryAssessment({ showToast }) {
  const [selectedFile, setSelectedFile] = useState(null);
  const [useSample, setUseSample] = useState(true);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [questions, setQuestions] = useState([]);
  const [answers, setAnswers] = useState({}); // { [questionId]: optionIndex }
  const [isSubmitted, setIsSubmitted] = useState(false);
  const [expandedCitations, setExpandedCitations] = useState({});

  const handleFileChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      if (!file.name.toLowerCase().endsWith('.pdf') && file.type !== 'application/pdf') {
        if (showToast) showToast('Only .pdf files are supported', 'error');
        return;
      }
      setSelectedFile(file);
      setUseSample(false);
      setError(null);
      if (showToast) showToast(`Selected ${file.name} for statutory ingestion`, 'success');
    }
  };

  const handleToggleSample = () => {
    const next = !useSample;
    setUseSample(next);
    if (next) {
      setSelectedFile(null);
      setError(null);
    }
  };

  // Priority 2: Ingestion & Inference pipeline via POST /generate-quiz with FormData
  const handleSynthesize = async (bypassCache = false) => {
    setLoading(true);
    setError(null);
    setQuestions([]); // STRICT RULE: zero out questions immediately
    setAnswers({});
    setIsSubmitted(false);
    setExpandedCitations({});

    try {
      let fileToUpload = selectedFile;
      if (!fileToUpload) {
        const blob = createSamplePdfBlob();
        fileToUpload = new File([blob], 'MoSPI_NSSTA_Technical_Compendium.pdf', { type: 'application/pdf' });
      }

      const formData = new FormData();
      formData.append('file', fileToUpload);

      const rawApiUrl = import.meta.env.VITE_API_URL || import.meta.env.VITE_API_BASE_URL || 'http://127.0.0.1:8000';
      const baseUrl = rawApiUrl.replace(/\/api\/?$/, '');
      const endpoint = `${baseUrl}/generate-quiz${bypassCache ? '?bypass_cache=true' : ''}`;

      // Genuine fetch with multipart boundary generated by browser (no manual Content-Type)
      const response = await fetch(endpoint, {
        method: 'POST',
        body: formData,
      });

      if (!response.ok) {
        let errorMsg = `Server responded with HTTP ${response.status} (${response.statusText})`;
        try {
          const errData = await response.json();
          if (errData && errData.detail) {
            errorMsg = typeof errData.detail === 'string' ? errData.detail : JSON.stringify(errData.detail);
          }
        } catch (_) {}
        throw new Error(errorMsg);
      }

      const data = await response.json();

      if (!data || !Array.isArray(data.questions) || data.questions.length === 0) {
        throw new Error('Backend returned invalid quiz schema: Missing or empty questions array.');
      }

      setQuestions(data.questions);
      if (showToast) {
        showToast(
          bypassCache
            ? 'Fresh Bloom-tiered assessment synthesized (Cache Bypassed)'
            : 'Synthesized 3 Bloom-tiered statutory questions via Ollama',
          'success'
        );
      }
    } catch (err) {
      console.error('Statutory Assessment Pipeline Failure:', err);
      // STRICT RULE: Zero out questions, set error state, NO static fallback hijacking!
      setQuestions([]);
      setError(err.message || 'Failed to communicate with ingestion engine.');
      if (showToast) {
        showToast('Assessment Ingestion Failed', 'error');
      }
    } finally {
      setLoading(false);
    }
  };

  const handleSelectOption = (questionId, optionIndex) => {
    if (isSubmitted) return; // Locked once submitted
    setAnswers((prev) => ({
      ...prev,
      [questionId]: optionIndex,
    }));
  };

  const toggleCitation = (questionId) => {
    setExpandedCitations((prev) => ({
      ...prev,
      [questionId]: !prev[questionId],
    }));
  };

  // Priority 3: Master submission action
  const handleSubmitAssessment = () => {
    if (questions.length === 0) return;
    const answeredCount = Object.keys(answers).length;
    if (answeredCount < questions.length) {
      if (showToast) {
        showToast(`Please respond to all ${questions.length} questions before submitting`, 'error');
      }
      return;
    }

    setIsSubmitted(true);

    // Expand statutory citation accordion for every question
    const allExpanded = {};
    questions.forEach((q) => {
      allExpanded[q.id] = true;
    });
    setExpandedCitations(allExpanded);

    if (showToast) {
      const correctCount = questions.filter((q) => answers[q.id] === q.correctIndex).length;
      showToast(`Assessment submitted: ${correctCount}/${questions.length} correct responses verified`, 'success');
    }
  };

  // Calculate score & Bloom tier itemization
  const correctCount = questions.filter((q) => answers[q.id] === q.correctIndex).length;

  const getBloomBadgeStyle = (levelStr = '') => {
    const lower = levelStr.toLowerCase();
    if (lower.includes('level 1') || lower.includes('recall')) {
      return 'bg-emerald-50 text-emerald-800 border-emerald-300 font-bold';
    }
    if (lower.includes('level 2') || lower.includes('analysis') || lower.includes('concept')) {
      return 'bg-blue-50 text-blue-800 border-blue-300 font-bold';
    }
    return 'bg-purple-50 text-purple-800 border-purple-300 font-bold';
  };

  return (
    <div className="space-y-6">
      
      {/* View Header & Ingestion Card */}
      <div className="rounded-2xl border border-[#f0e6dc] bg-white p-6 shadow-sm">
        <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
          <div>
            <div className="flex items-center gap-2.5">
              <div className="w-9 h-9 rounded-xl bg-[#1d5ba5]/10 flex items-center justify-center">
                <FileText className="w-5 h-5 text-[#1d5ba5]" />
              </div>
              <h2 className="text-xl font-bold text-slate-900">
                Statutory Assessment Synthesizer (PyMuPDF + Ollama)
              </h2>
            </div>
            <p className="text-xs text-slate-500 mt-1">
              Observable end-to-end extraction pipeline from official MoSPI Gazette circulars into Bloom-tiered psychometric evaluations.
            </p>
          </div>

          <div className="flex items-center gap-3">
            <label className="flex items-center gap-2 cursor-pointer bg-[#fdf8f3] px-4 py-2 rounded-full border border-[#f0e6dc] text-xs font-semibold text-slate-700 hover:bg-orange-50/50 transition-colors">
              <input
                type="checkbox"
                checked={useSample}
                onChange={handleToggleSample}
                className="rounded border-slate-300 text-[#f58220] focus:ring-[#f58220] h-4 w-4 accent-[#f58220]"
              />
              <span>Use Official MoSPI NSSTA Compendium</span>
            </label>
          </div>
        </div>

        {/* Upload Dropzone & Action Controls */}
        <div className="mt-5 grid grid-cols-1 md:grid-cols-2 gap-4">
          <div
            className={`border-2 border-dashed rounded-2xl p-5 text-center transition-colors ${
              selectedFile
                ? 'border-[#1d5ba5] bg-[#1d5ba5]/5'
                : 'border-[#e2d7cc] hover:border-[#1d5ba5]/50 bg-[#fdf8f3]/50'
            }`}
          >
            <input
              type="file"
              accept=".pdf"
              id="pdfUploadInput"
              onChange={handleFileChange}
              className="hidden"
            />
            <label htmlFor="pdfUploadInput" className="cursor-pointer block">
              <Upload className="w-8 h-8 text-[#1d5ba5] mx-auto mb-2" />
              <p className="text-xs font-bold text-slate-800">
                {selectedFile ? selectedFile.name : (useSample ? 'MoSPI_NSSTA_Technical_Compendium.pdf (Active Default)' : 'Upload Statutory Circular / Gazette PDF')}
              </p>
              <p className="text-[11px] text-slate-500 mt-0.5">
                PyMuPDF extracts text, verifies &gt; 100 characters, and slices 4,500 chars clean context
              </p>
            </label>
          </div>

          <div className="flex flex-col justify-between p-4 rounded-2xl border border-[#f0e6dc] bg-[#fdf8f3]/60">
            <div>
              <p className="text-xs font-bold text-slate-800 mb-1">Pedagogical Bloom Taxonomy Mapping</p>
              <div className="flex flex-wrap gap-2 text-[11px]">
                <span className="px-2.5 py-0.5 rounded-full border bg-emerald-50 text-emerald-800 border-emerald-200 font-semibold">
                  Level 1: Recall
                </span>
                <span className="px-2.5 py-0.5 rounded-full border bg-blue-50 text-blue-800 border-blue-200 font-semibold">
                  Level 2: Conceptual Analysis
                </span>
                <span className="px-2.5 py-0.5 rounded-full border bg-purple-50 text-purple-800 border-purple-200 font-semibold">
                  Level 3: Procedural Application
                </span>
              </div>
            </div>

            <div className="mt-4 flex flex-wrap gap-2">
              {/* Primary Synthesize Button */}
              <button
                type="button"
                onClick={() => handleSynthesize(false)}
                disabled={loading}
                className="flex-1 flex items-center justify-center gap-2 rounded-full bg-[#f58220] hover:bg-[#e07116] px-5 py-2.5 text-xs font-bold text-white shadow-sm disabled:opacity-60 transition-all cursor-pointer"
              >
                <Sparkles className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
                <span>{loading ? 'Synthesizing...' : 'Synthesize Assessment'}</span>
              </button>

              {/* Priority 3: Cache Bypass Regeneration Button */}
              <button
                type="button"
                onClick={() => handleSynthesize(true)}
                disabled={loading}
                className="flex items-center justify-center gap-1.5 rounded-full bg-[#1d5ba5] hover:bg-[#164a87] px-4 py-2.5 text-xs font-bold text-white shadow-sm disabled:opacity-60 transition-all cursor-pointer"
                title="Bypass cache and force fresh inference from local Ollama"
              >
                <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin' : ''}`} />
                <span>Generate New Assessment</span>
              </button>
            </div>
          </div>
        </div>

      </div>

      {/* Priority 2: Active Spinner with Exact Text */}
      {loading && (
        <div className="rounded-2xl border border-blue-200 bg-blue-50/70 p-6 text-center space-y-3 animate-in fade-in">
          <div className="w-10 h-10 border-3 border-[#1d5ba5] border-t-transparent rounded-full animate-spin mx-auto"></div>
          <p className="text-sm font-bold text-[#1d5ba5]">
            PyMuPDF extracting statutory stream & Ollama synthesizing...
          </p>
          <p className="text-xs text-slate-500">
            Parsing PDF character stream, enforcing 3 Bloom tiers, and validating Pydantic JSON schema (Timeout: 180s).
          </p>
        </div>
      )}

      {/* Priority 2: CRITICAL ERROR REPORTING BANNER (NO STATIC FALLBACK HIJACKING) */}
      {error && !loading && (
        <div className="rounded-2xl border-2 border-rose-300 bg-rose-50 p-6 shadow-sm space-y-4">
          <div className="flex items-start gap-3">
            <AlertOctagon className="w-6 h-6 text-rose-600 shrink-0 mt-0.5" />
            <div className="space-y-1">
              <h4 className="text-sm font-extrabold text-rose-900">
                Pipeline Ingestion Error — Ingestion Pipeline Halted
              </h4>
              <p className="text-xs font-mono text-rose-800 bg-rose-100/80 p-3 rounded-xl border border-rose-200 break-words">
                {error}
              </p>
              <p className="text-xs text-rose-700 pt-1">
                Static fallback question hijacking has been disabled. The backend failure is reported above for transparent inspection.
              </p>
            </div>
          </div>

          <div className="flex items-center gap-3 pt-1">
            <button
              type="button"
              onClick={() => handleSynthesize(false)}
              className="flex items-center gap-2 px-5 py-2.5 rounded-full bg-rose-600 hover:bg-rose-700 text-white text-xs font-bold shadow-sm transition-all cursor-pointer"
            >
              <RefreshCw className="w-4 h-4" />
              <span>Retry Ingestion</span>
            </button>
          </div>
        </div>
      )}

      {/* Questions List & Interactive Assessment */}
      {!loading && !error && questions.length > 0 && (
        <div className="space-y-5">
          
          <div className="flex items-center justify-between">
            <h3 className="text-base font-bold text-slate-900 flex items-center gap-2">
              <BookOpen className="w-5 h-5 text-[#1d5ba5]" />
              <span>Interactive Statutory Competency Assessment</span>
            </h3>
            <span className="text-xs font-bold px-3 py-1 rounded-full bg-orange-50 text-[#f58220] border border-orange-200">
              {questions.length} Items Loaded
            </span>
          </div>

          {/* Question Cards */}
          {questions.map((q, qIndex) => {
            const chosenIndex = answers[q.id];
            const isAnswered = chosenIndex !== undefined;
            const isCorrect = isSubmitted && chosenIndex === q.correctIndex;
            const isCitationOpen = !!expandedCitations[q.id];

            return (
              <div
                key={q.id || qIndex}
                className={`rounded-2xl border bg-white p-6 shadow-sm transition-all space-y-4 ${
                  isSubmitted
                    ? isCorrect
                      ? 'border-emerald-200 bg-emerald-50/10'
                      : 'border-rose-200 bg-rose-50/10'
                    : 'border-[#f0e6dc]'
                }`}
              >
                {/* Question Header & Bloom Tier */}
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="font-mono text-xs font-bold px-2.5 py-0.5 rounded-md bg-[#fdf8f3] text-slate-700 border border-[#f0e6dc]">
                      {q.id || `KSI-00${qIndex + 1}`}
                    </span>
                    <span className={`text-xs px-2.5 py-0.5 rounded-full border ${getBloomBadgeStyle(q.level)}`}>
                      {q.level}
                    </span>
                    {q.domain && (
                      <span className="hidden sm:inline text-[11px] text-slate-500 font-medium">
                        • {q.domain}
                      </span>
                    )}
                  </div>

                  {/* Submission Status Pill */}
                  {isSubmitted && (
                    <span
                      className={`text-xs font-bold px-2.5 py-0.5 rounded-full border flex items-center gap-1 ${
                        isCorrect
                          ? 'bg-emerald-50 text-emerald-700 border-emerald-200'
                          : 'bg-rose-50 text-rose-700 border-rose-200'
                      }`}
                    >
                      {isCorrect ? <CheckCircle2 className="w-3.5 h-3.5" /> : <XCircle className="w-3.5 h-3.5" />}
                      <span>{isCorrect ? 'Correct Response' : 'Incorrect Response'}</span>
                    </span>
                  )}
                </div>

                {/* Question Stem */}
                <h4 className="text-sm font-bold text-slate-900 leading-relaxed">
                  {qIndex + 1}. {q.question}
                </h4>

                {/* Radio Options Group */}
                <div className="space-y-2.5">
                  {q.options.map((opt, optIndex) => {
                    const isSelected = chosenIndex === optIndex;
                    const isOptionCorrect = q.correctIndex === optIndex;

                    // Priority 3 styling:
                    // Correct answer highlighted in emerald green once submitted
                    // Wrong user selection highlighted in red
                    let optionClasses = 'border-[#f0e6dc] bg-[#fdf8f3]/30 text-slate-700 hover:border-slate-300';

                    if (isSubmitted) {
                      if (isOptionCorrect) {
                        optionClasses = 'border-emerald-500 bg-emerald-50 text-emerald-950 font-semibold shadow-xs';
                      } else if (isSelected && !isOptionCorrect) {
                        optionClasses = 'border-rose-500 bg-rose-50 text-rose-950 font-semibold shadow-xs';
                      } else {
                        optionClasses = 'border-slate-200 bg-slate-50/50 text-slate-400 opacity-60';
                      }
                    } else if (isSelected) {
                      optionClasses = 'border-[#f58220] bg-orange-50/60 text-slate-900 font-semibold shadow-xs';
                    }

                    return (
                      <label
                        key={optIndex}
                        onClick={() => handleSelectOption(q.id, optIndex)}
                        className={`flex items-start gap-3 p-3.5 rounded-xl border text-xs transition-all ${
                          isSubmitted ? 'cursor-default' : 'cursor-pointer'
                        } ${optionClasses}`}
                      >
                        <input
                          type="radio"
                          name={`quiz_${q.id}`}
                          value={optIndex}
                          checked={isSelected}
                          disabled={isSubmitted}
                          onChange={() => handleSelectOption(q.id, optIndex)}
                          className="mt-0.5 h-4 w-4 text-[#f58220] border-slate-300 focus:ring-[#f58220] accent-[#f58220] disabled:opacity-75"
                        />
                        <span className="flex-1 leading-relaxed">{opt}</span>
                        {isSubmitted && isOptionCorrect && (
                          <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
                        )}
                        {isSubmitted && isSelected && !isOptionCorrect && (
                          <XCircle className="w-4 h-4 text-rose-600 shrink-0" />
                        )}
                      </label>
                    );
                  })}
                </div>

                {/* Citation Accordion */}
                <div className="pt-2 border-t border-[#f0e6dc]">
                  <button
                    type="button"
                    onClick={() => toggleCitation(q.id)}
                    className="flex items-center justify-between w-full text-xs font-bold text-[#1d5ba5] hover:text-[#164a87] cursor-pointer"
                  >
                    <span>📜 Statutory Citation & Compendium Rationale</span>
                    {isCitationOpen ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
                  </button>

                  {isCitationOpen && (
                    <div className="mt-2.5 p-3.5 rounded-xl bg-[#fdf8f3] border border-[#f0e6dc] text-xs text-slate-700 leading-relaxed">
                      <p className="font-semibold text-slate-900 mb-1">Source Citation:</p>
                      <p>{q.citation}</p>
                      {isSubmitted && (
                        <p className="mt-2 font-bold text-emerald-800">
                          Verified Correct Choice: Option {String.fromCharCode(65 + q.correctIndex)} — {q.options[q.correctIndex]}
                        </p>
                      )}
                    </div>
                  )}
                </div>

              </div>
            );
          })}

          {/* Master Action: Single "Submit Competency Assessment" button */}
          {!isSubmitted && (
            <div className="pt-2 flex justify-end">
              <button
                type="button"
                onClick={handleSubmitAssessment}
                className="flex items-center gap-2 px-8 py-3.5 rounded-full bg-[#1d5ba5] hover:bg-[#164a87] text-white text-xs font-bold shadow-md transition-all cursor-pointer"
              >
                <Send className="w-4 h-4 text-blue-200" />
                <span>Submit Competency Assessment</span>
              </button>
            </div>
          )}

          {/* Priority 3: Completion Summary Card */}
          {isSubmitted && (
            <div className="rounded-2xl border-2 border-emerald-300 bg-emerald-50/70 p-6 shadow-sm space-y-4 animate-in fade-in">
              <div className="flex items-center justify-between flex-wrap gap-3">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-xl bg-emerald-600 text-white flex items-center justify-center shadow-sm">
                    <Award className="w-6 h-6" />
                  </div>
                  <div>
                    <h4 className="text-base font-extrabold text-emerald-950">
                      Assessment Complete — {correctCount}/3 Verified
                    </h4>
                    <p className="text-xs text-emerald-800 mt-0.5 font-medium">
                      Psychometric statutory evaluation verified against MoSPI compendium standards.
                    </p>
                  </div>
                </div>

                <div className="text-right">
                  <span className="text-2xl font-black font-mono text-emerald-900">
                    {Math.round((correctCount / 3) * 100)}%
                  </span>
                  <p className="text-[10px] uppercase font-bold text-emerald-700 tracking-wider">
                    Score Attainment
                  </p>
                </div>
              </div>

              {/* Itemized Bloom-Tier Breakdown */}
              <div className="border-t border-emerald-200/80 pt-3 space-y-2">
                <p className="text-xs font-extrabold uppercase tracking-wider text-emerald-900">
                  Itemized Bloom-Tier Breakdown:
                </p>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-2.5 text-xs">
                  {questions.map((q, idx) => {
                    const isQCorrect = answers[q.id] === q.correctIndex;
                    return (
                      <div
                        key={q.id || idx}
                        className={`p-3 rounded-xl border flex items-center justify-between ${
                          isQCorrect
                            ? 'bg-white border-emerald-300 text-emerald-900'
                            : 'bg-white border-rose-300 text-rose-900'
                        }`}
                      >
                        <span className="font-bold">{q.level}</span>
                        <span
                          className={`inline-flex items-center gap-1 font-bold text-xs px-2 py-0.5 rounded-full ${
                            isQCorrect
                              ? 'bg-emerald-100 text-emerald-800'
                              : 'bg-rose-100 text-rose-800'
                          }`}
                        >
                          {isQCorrect ? (
                            <>
                              <CheckCircle2 className="w-3 h-3" />
                              <span>Correct</span>
                            </>
                          ) : (
                            <>
                              <XCircle className="w-3 h-3" />
                              <span>Incorrect</span>
                            </>
                          )}
                        </span>
                      </div>
                    );
                  })}
                </div>
              </div>

              {/* Generate New Assessment Action inside Summary Card */}
              <div className="pt-2 flex justify-end">
                <button
                  type="button"
                  onClick={() => handleSynthesize(true)}
                  disabled={loading}
                  className="flex items-center gap-2 px-6 py-2.5 rounded-full bg-[#1d5ba5] hover:bg-[#164a87] text-white text-xs font-bold shadow-sm transition-all cursor-pointer"
                >
                  <RefreshCw className="w-3.5 h-3.5" />
                  <span>Generate New Assessment (Force Fresh Items)</span>
                </button>
              </div>

            </div>
          )}

        </div>
      )}

      {/* Initial Empty State before any synthesis */}
      {!loading && !error && questions.length === 0 && (
        <div className="rounded-2xl border border-[#f0e6dc] bg-white p-12 text-center text-slate-500">
          <HelpCircle className="w-12 h-12 text-slate-300 mx-auto mb-2" />
          <p className="text-sm font-bold text-slate-700">No Assessment Synthesized Yet</p>
          <p className="text-xs text-slate-400 mt-1 max-w-md mx-auto">
            Click "Synthesize Assessment" above to extract statutory clauses via PyMuPDF and synthesize 3 Bloom-tiered evaluation questions with local Ollama.
          </p>
        </div>
      )}

    </div>
  );
}
